// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC17CGWEM1F6jSOitOHGmEHCsvqIzj-WPw',
    appId: '1:694777185777:web:272e736d7804b29cb3b050',
    messagingSenderId: '694777185777',
    projectId: 'myac2-3dc53',
    authDomain: 'myac2-3dc53.firebaseapp.com',
    storageBucket: 'myac2-3dc53.appspot.com',
    measurementId: 'G-PJL1F5DXS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp3vzqjRV2nwZECta20TNI-g4L0GIVpbw',
    appId: '1:694777185777:android:b7bcee71ef0f6c2db3b050',
    messagingSenderId: '694777185777',
    projectId: 'myac2-3dc53',
    storageBucket: 'myac2-3dc53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGbxyt3IUBaCGRBfk6xLaQWeljQmMXfq8',
    appId: '1:694777185777:ios:ec7078ea8608644fb3b050',
    messagingSenderId: '694777185777',
    projectId: 'myac2-3dc53',
    storageBucket: 'myac2-3dc53.appspot.com',
    iosClientId: '694777185777-i0aem6a4ap2beajuk9ddpodki7gtpcit.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGbxyt3IUBaCGRBfk6xLaQWeljQmMXfq8',
    appId: '1:694777185777:ios:eaf704f7b51df9bfb3b050',
    messagingSenderId: '694777185777',
    projectId: 'myac2-3dc53',
    storageBucket: 'myac2-3dc53.appspot.com',
    iosClientId: '694777185777-nqugm37eb9i55oqigc9nu4qcpv4qksfr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
